package com.example.util

import android.content.Context
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

data class LanguageOption(val code: String, val name: String, val localName: String)

object LanguageManager {
    var currentLanguage by mutableStateOf("system")

    val supportedLanguages = listOf(
        LanguageOption("system", "System Default", "Default"),
        LanguageOption("en", "English", "English"),
        LanguageOption("es", "Spanish", "Español"),
        LanguageOption("pt", "Portuguese", "Português"),
        LanguageOption("hi", "Hindi", "हिन्दी"),
        LanguageOption("ar", "Arabic", "العربية"),
        LanguageOption("fr", "French", "Français"),
        LanguageOption("de", "German", "Deutsch"),
        LanguageOption("id", "Indonesian", "Bahasa Indonesia"),
        LanguageOption("tr", "Turkish", "Türkçe"),
        LanguageOption("ja", "Japanese", "日本語")
    )

    fun initialize(context: Context) {
        val prefs = context.getSharedPreferences("cueflow_prefs", Context.MODE_PRIVATE)
        currentLanguage = prefs.getString("app_language", "system") ?: "system"
    }

    fun saveLanguage(context: Context, lang: String) {
        currentLanguage = lang
        context.getSharedPreferences("cueflow_prefs", Context.MODE_PRIVATE)
            .edit()
            .putString("app_language", lang)
            .apply()
    }

    private val translations = mapOf(
        "en" to mapOf(
            "search_hint" to "Search title or content...",
            "all_scripts" to "All Scripts",
            "folders" to "Folders",
            "reset_filters" to "Reset Filters",
            "delete" to "Delete",
            "cancel" to "Cancel",
            "create" to "Create",
            "delete_script_title" to "Delete Script",
            "delete_script_confirm" to "Are you sure you want to delete this script? This action cannot be undone.",
            "delete_folder_title" to "Delete Folder",
            "delete_folder_confirm" to "Delete this folder? Scripts inside it will be kept and moved to All Scripts.",
            "create_folder_title" to "Create New Folder",
            "folder_name_hint" to "Folder Name (e.g., YouTube videos)",
            "folder_name_label" to "Folder Name",
            "edit_script_tab" to "Edit Script",
            "saved_key_points_tab" to "Saved Key Points",
            "tap_to_jump" to "Tap to jump & edit",
            "script_empty_state" to "Script is empty. Go to 'Edit Script' tab to write some content.",
            "auto_scroll_speed" to "Auto-scroll seed speed",
            "teleprompter_text_size" to "Teleprompter text size",
            "background_transparency" to "Background transparency",
            "text_color_preset" to "Text Color Preset or Custom Hex",
            "visual_customization" to "Visual Customization",
            "select_theme" to "Select App Color Theme",
            "custom_accent" to "Custom Accent Highlights",
            "save_apply" to "Save & Apply Customization",
            "text_direction" to "Text Direction (RTL Arabic/Hebrew support)",
            "text_direction_auto" to "AUTO DETECT",
            "text_direction_ltr" to "FORCE LTR",
            "text_direction_rtl" to "FORCE RTL",
            "mirror_text" to "Mirror Text View",
            "floating_mode" to "Floating overlay mode",
            "start_floating" to "Start Floating Prompter",
            "launch_prompter" to "Launch Teleprompter",
            "select_tone" to "Select Style / Tone",
            "discard_changes" to "Discard Changes",
            "accept_apply" to "Accept & Apply",
            "text_size" to "Text Size",
            "backdrop_opacity" to "Backdrop Opacity",
            "window_opacity" to "Window Opacity",
            "speech_color" to "Speech Text Color",
            "backdrop_theme" to "Backdrop Color Theme",
            "default_alignment" to "Default Screen Alignment",
            "scroll_speed" to "Scroll Speed",
            "save_settings" to "Save & Apply Settings",
            "words" to "Words",
            "characters" to "Characters",
            "voice_calibration" to "Voice Style Calibration",
            "voice_sensitivity" to "Voice Sensitivity",
            "pause_threshold" to "Pause Detection Threshold",
            "min_speed" to "Minimum Speed (Auto-Crawl Fallback)",
            "max_speed" to "Maximum Speed (Paragraph Jumps)",
            "authorize_now" to "Authorize Now",
            "retry_connection" to "Retry Connection",
            "language_settings" to "Language Settings",
            "app_language" to "App Interface Language",
            "language_description" to "Override default phone language setting.",
            "all_count" to "Scripts",
            "no_scripts_found" to "No scripts match your current filters.",
            "first_script_prompt" to "Tap the '+' button to write your first teleprompter script!",
            "unassigned_folder" to "None (All Scripts)"
        ),
        "es" to mapOf(
            "search_hint" to "Buscar título o contenido...",
            "all_scripts" to "Todos los guiones",
            "folders" to "Carpetas",
            "reset_filters" to "Restablecer filtros",
            "delete" to "Eliminar",
            "cancel" to "Cancelar",
            "create" to "Crear",
            "delete_script_title" to "Eliminar guion",
            "delete_script_confirm" to "¿Está seguro de que desea eliminar este guion? Esta acción no se puede deshacer.",
            "delete_folder_title" to "Eliminar carpeta",
            "delete_folder_confirm" to "¿Eliminar esta carpeta? Los guiones que contiene se conservarán y pasarán a Todos los guiones.",
            "create_folder_title" to "Crear nueva carpeta",
            "folder_name_hint" to "Nombre de carpeta (ej. Videos de YouTube)",
            "folder_name_label" to "Nombre de carpeta",
            "edit_script_tab" to "Editar guion",
            "saved_key_points_tab" to "Puntos clave guardados",
            "tap_to_jump" to "Toca para saltar y editar",
            "script_empty_state" to "El guion está vacío. Ve a la pestaña 'Editar guion' para escribir contenido.",
            "auto_scroll_speed" to "Velocidad de auto-desplazamiento",
            "teleprompter_text_size" to "Tamaño de texto del teleprompter",
            "background_transparency" to "Transparencia de fondo",
            "text_color_preset" to "Preselección de color de texto o Hex personalizado",
            "visual_customization" to "Personalización visual",
            "select_theme" to "Seleccionar tema de color de la aplicación",
            "custom_accent" to "Aspectos destacados de acento personalizado",
            "save_apply" to "Guardar y aplicar personalización",
            "text_direction" to "Dirección del texto (Soporte RTL árabe/hebreo)",
            "text_direction_auto" to "AUTO DETECTAR",
            "text_direction_ltr" to "FORZAR LTR",
            "text_direction_rtl" to "FORZAR RTL",
            "mirror_text" to "Reflejar vista de texto (Espejo)",
            "floating_mode" to "Modo flotante superpuesto",
            "start_floating" to "Iniciar apuntador flotante",
            "launch_prompter" to "Iniciar teleprompter",
            "select_tone" to "Seleccionar estilo / tono",
            "discard_changes" to "Descartar cambios",
            "accept_apply" to "Aceptar y aplicar",
            "text_size" to "Tamaño del texto",
            "backdrop_opacity" to "Opacidad del fondo",
            "window_opacity" to "Opacidad de la ventana",
            "speech_color" to "Color del texto hablado",
            "backdrop_theme" to "Tema de color del fondo",
            "default_alignment" to "Alineación de pantalla predeterminada",
            "scroll_speed" to "Velocidade de rolagem",
            "save_settings" to "Guardar y aplicar configuración",
            "words" to "Palabras",
            "characters" to "Caracteres",
            "voice_calibration" to "Calibración del estilo de voz",
            "voice_sensitivity" to "Sensibilidad de voz",
            "pause_threshold" to "Umbral de detección de pausa",
            "min_speed" to "Velocidad mínima (Retroceso de auto-rastreo)",
            "max_speed" to "Velocidad máxima (Grandes saltos)",
            "authorize_now" to "Autorizar ahora",
            "retry_connection" to "Reintentar conexión",
            "language_settings" to "Ajustes de idioma",
            "app_language" to "Idioma de la interfaz",
            "language_description" to "Anular el ajuste de idioma predeterminado del teléfono.",
            "all_count" to "Guiones",
            "no_scripts_found" to "Ningún guion coincide con los filtros actuales.",
            "first_script_prompt" to "¡Toca el botón '+' para escribir tu primer guion de teleprompter!",
            "unassigned_folder" to "Ninguno (Todos los guiones)"
        ),
        "pt" to mapOf(
            "search_hint" to "Buscar título ou conteúdo...",
            "all_scripts" to "Todos os roteiros",
            "folders" to "Pastas",
            "reset_filters" to "Redefinir filtros",
            "delete" to "Excluir",
            "cancel" to "Cancelar",
            "create" to "Criar",
            "delete_script_title" to "Excluir roteiro",
            "delete_script_confirm" to "Tem certeza de que deseja excluir este roteiro? Esta ação não pode ser desfeita.",
            "delete_folder_title" to "Excluir pasta",
            "delete_folder_confirm" to "Excluir esta pasta? Os roteiros nela serão mantidos e movidos para Todos os roteiros.",
            "create_folder_title" to "Criar nova pasta",
            "folder_name_hint" to "Nome da pasta (ex., vídeos do YouTube)",
            "folder_name_label" to "Nome da pasta",
            "edit_script_tab" to "Editar roteiro",
            "saved_key_points_tab" to "Pontos-chave salvos",
            "tap_to_jump" to "Toque para saltar e editar",
            "script_empty_state" to "O roteiro está vazio. Vá para a guia 'Editar roteiro' para escrever conteúdo.",
            "auto_scroll_speed" to "Velocidade de rolagem automática",
            "teleprompter_text_size" to "Tamanho do texto do teleprompter",
            "background_transparency" to "Transparência do fundo",
            "text_color_preset" to "Predefinição de cor de texto ou Hex personalizado",
            "visual_customization" to "Personalização visual",
            "select_theme" to "Selecionar tema de cores do aplicativo",
            "custom_accent" to "Destaques de cores personalizadas",
            "save_apply" to "Salvar e aplicar personalização",
            "text_direction" to "Direção do texto (Suporte RTL árabe/hebraico)",
            "text_direction_auto" to "AUTO DETECTAR",
            "text_direction_ltr" to "FORÇAR LTR",
            "text_direction_rtl" to "FORÇAR RTL",
            "mirror_text" to "Espelhar visualização de texto",
            "floating_mode" to "Modo flutuante sobreposto",
            "start_floating" to "Iniciar ponto flutuante",
            "launch_prompter" to "Iniciar teleprompter",
            "select_tone" to "Selecionar estilo / tom",
            "discard_changes" to "Descartar alterações",
            "accept_apply" to "Aceitar e aplicar",
            "text_size" to "Tamanho do texto",
            "backdrop_opacity" to "Opacidade do fundo",
            "window_opacity" to "Opacidade da janela",
            "speech_color" to "Cor de texto do discurso",
            "backdrop_theme" to "Tema de cores do fundo",
            "default_alignment" to "Alinhamento padrão da tela",
            "scroll_speed" to "Velocidade de rolagem",
            "save_settings" to "Salvar e aplicar configurações",
            "words" to "Palavras",
            "characters" to "Caracteres",
            "voice_calibration" to "Calibragem do estilo de voz",
            "voice_sensitivity" to "Sensibilidade de voz",
            "pause_threshold" to "Limiar de detecção de pausa",
            "min_speed" to "Velocidade mínima (Retrocesso automático)",
            "max_speed" to "Velocidade máxima (Saltos de parágrafo)",
            "authorize_now" to "Autorizar agora",
            "retry_connection" to "Repetir conexão",
            "language_settings" to "Configurações de idioma",
            "app_language" to "Idioma da interface",
            "language_description" to "Substituir a configuração de idioma padrão do telefone.",
            "all_count" to "Roteiros",
            "no_scripts_found" to "Nenhum roteiro corresponde aos filtros atuais.",
            "first_script_prompt" to "Toque no botão '+' para programar seu primeiro roteiro de teleprompter!",
            "unassigned_folder" to "Nenhum (Todos os roteiros)"
        ),
        "hi" to mapOf(
            "search_hint" to "शीर्षक या सामग्री खोजें...",
            "all_scripts" to "सभी स्क्रिप्ट",
            "folders" to "फ़ोल्डर",
            "reset_filters" to "फ़िल्टर रीसेट करें",
            "delete" to "हटाएं",
            "cancel" to "रद्द करें",
            "create" to "बनाएं",
            "delete_script_title" to "स्क्रिप्ट हटाएं",
            "delete_script_confirm" to "क्या आप वाकई इस स्क्रिप्ट को हटाना चाहते हैं? यह क्रिया रद्द नहीं की जा सकती।",
            "delete_folder_title" to "फ़ोल्डर हटाएं",
            "delete_folder_confirm" to "यह फ़ोल्डर हटाएँ? इसके अंदर की स्क्रिप्ट सुरक्षित रहेंगी और सभी स्क्रिप्ट में चली जाएँगी।",
            "create_folder_title" to "नया फ़ोल्डर बनाएं",
            "folder_name_hint" to "फ़ोल्डर का नाम (जैसे, YouTube वीडियो)",
            "folder_name_label" to "फ़ोल्डर का नाम",
            "edit_script_tab" to "स्क्रिप्ट संपादित करें",
            "saved_key_points_tab" to "सुरक्षित मुख्य बिंदु",
            "tap_to_jump" to "संपादित करने के लिए टैप करें",
            "script_empty_state" to "स्क्रिप्ट खाली है। सामग्री लिखने के लिए 'स्क्रिप्ट संपादित करें' टैब पर जाएं।",
            "auto_scroll_speed" to "ऑटो-स्क्रॉल गति",
            "teleprompter_text_size" to "टेलीप्रॉम्प्टर टेक्स्ट आकार",
            "background_transparency" to "पृष्ठभूमि पारदर्शिता",
            "text_color_preset" to "टेक्स्ट रंग प्रीसेट या कस्टम हेक्स",
            "visual_customization" to "दृश्य अनुकूलन",
            "select_theme" to "ऐप का रंग विषय चुनें",
            "custom_accent" to "कस्टम एक्सेंट हाइलाइट्स",
            "save_apply" to "अनुकूलन सहेजें और लागू करें",
            "text_direction" to "पाठ दिशा (RTL अरबी/हिब्रू समर्थन)",
            "text_direction_auto" to "ऑटो डिटेक्ट",
            "text_direction_ltr" to "LTR बाध्य करें",
            "text_direction_rtl" to "RTL बाध्य करें",
            "mirror_text" to "टेक्स्ट व्यू मिरर करें",
            "floating_mode" to "फ्लोटिंग ओवरले मोड",
            "start_floating" to "फ्لوटिंग प्रॉम्प्टर शुरू करें",
            "launch_prompter" to "टेलीप्रॉम्प्टर शुरू करें",
            "select_tone" to "शैली / टोन चुनें",
            "discard_changes" to "परिवर्तन छोड़ें",
            "accept_apply" to "स्वीकार और लागू करें",
            "text_size" to "पाठ का आकार",
            "backdrop_opacity" to "पृष्ठभूमि अपारदर्शिता",
            "window_opacity" to "विंडो अपारदर्शिता",
            "speech_color" to "भाषण पाठ का रंग",
            "backdrop_theme" to "पृष्ठभूमि रंग थीम",
            "default_alignment" to "डिफ़ॉल्ट स्क्रीन अलाइनमेंट",
            "scroll_speed" to "स्क्रॉल गति",
            "save_settings" to "सेटिंग्स सहेजें और लागू करें",
            "words" to "शब्द",
            "characters" to "अक्षर",
            "voice_calibration" to "आवाज शैली अंशांकन",
            "voice_sensitivity" to "आवाज संवेदनशीलता",
            "pause_threshold" to "विराम पहचान सीमा",
            "min_speed" to "न्यूनतम गति (ऑटो-स्क्रॉल बैकअप)",
            "max_speed" to "अधिकतम गति (पैराग्राफ जंप)",
            "authorize_now" to "अभी अधिकृत करें",
            "retry_connection" to "पुनः प्रयास करें",
            "language_settings" to "भाषा सेटिंग्स",
            "app_language" to "ऐप की भाषा",
            "language_description" to "फ़ोन की डिफ़ॉल्ट भाषा सेटिंग को बदलें।",
            "all_count" to "स्क्रिप्ट",
            "no_scripts_found" to "कोई भी स्क्रिप्ट आपके वर्तमान फ़िल्टर से मेल नहीं खाती।",
            "first_script_prompt" to "अपनी पहली टेलीप्रॉम्प्टर स्क्रिप्ट लिखने के लिए '+' बटन दबाएं!",
            "unassigned_folder" to "कोई नहीं (सभी स्क्रिप्ट)"
        ),
        "ar" to mapOf(
            "search_hint" to "البحث عن العنوان أو المحتوى...",
            "all_scripts" to "جميع النصوص",
            "folders" to "المجلدات",
            "reset_filters" to "إعادة تعيين الفلاتر",
            "delete" to "حذف",
            "cancel" to "إلغاء",
            "create" to "إنشاء",
            "delete_script_title" to "حذف النص",
            "delete_script_confirm" to "هل أنت متأكد أنك تريد حذف هذا النص؟ لا يمكن التراجع عن هذا الإجراء.",
            "delete_folder_title" to "حذف المجلد",
            "delete_folder_confirm" to "حذف هذا المجلد؟ ستبقى النصوص الموجودة بداخله وسيتم نقلها إلى كل النصوص.",
            "create_folder_title" to "إنشاء مجلد جديد",
            "folder_name_hint" to "اسم المجلد (مثل فيديو يوتيوب)",
            "folder_name_label" to "اسم المجلد",
            "edit_script_tab" to "تعديل النص",
            "saved_key_points_tab" to "النقاط الرئيسية المحفوظة",
            "tap_to_jump" to "انقر للانتقال والتعديل",
            "script_empty_state" to "المحتوى فارغ. اذهب إلى تبويب 'تعديل النص' لكتابة بعض المحتوى.",
            "auto_scroll_speed" to "سرعة التمرير التلقائي",
            "teleprompter_text_size" to "حجم خط الملقن",
            "background_transparency" to "شفافية الخلفية",
            "text_color_preset" to "لون النص الجاهز أو مخصص Hex",
            "visual_customization" to "التخصيص البصري",
            "select_theme" to "اختر مظهر ألوان التطبيق",
            "custom_accent" to "ألوان تمييز مخصصة",
            "save_apply" to "حفظ وتطبيق التغييرات",
            "text_direction" to "اتجاه النص (دعم العربية/العبرية RTL)",
            "text_direction_auto" to "كشف تلقائي",
            "text_direction_ltr" to "فرض من اليسار لليمين",
            "text_direction_rtl" to "فرض من اليمين لليسار",
            "mirror_text" to "مرآة عرض النص",
            "floating_mode" to "نمط النافذة العائمة",
            "start_floating" to "بدء الملقن العائم",
            "launch_prompter" to "بدء تشغيل الملقن",
            "select_tone" to "اختر النبرة / الأسلوب",
            "discard_changes" to "تجاهل التغييرات",
            "accept_apply" to "قبول وتطبيق",
            "text_size" to "حجم النص",
            "backdrop_opacity" to "شفافية خلفية النص",
            "window_opacity" to "شفافية النافذة",
            "speech_color" to "لون النص المنطوق",
            "backdrop_theme" to "مظهر ألوان خلفية النص",
            "default_alignment" to "محاذاة الشاشة الافتراضية",
            "scroll_speed" to "سرعة التمرير",
            "save_settings" to "حفظ وتطبيق الإعدادات",
            "words" to "كلمة",
            "characters" to "حرف",
            "voice_calibration" to "معايرة أسلوب الصوت",
            "voice_sensitivity" to "حساسية الصوت",
            "pause_threshold" to "حد كشف التوقف مؤقتًا",
            "min_speed" to "السرعة الدنيا (التمرير التلقائي الاحتياطي)",
            "max_speed" to "السرعة القصوى (قفزات الفقرة)",
            "authorize_now" to "التصريح الآن",
            "retry_connection" to "إعادة محاولة الاتصال",
            "language_settings" to "إعدادات اللغة",
            "app_language" to "لغة واجهة التطبيق",
            "language_description" to "تجاوز إعداد لغة الهاتف الافتراضية.",
            "all_count" to "النصوص",
            "no_scripts_found" to "لا توجد نصوص تطابق الفلاتر الحالية.",
            "first_script_prompt" to "انقر على زر '+' لكتابة أول نص ملقن لك!",
            "unassigned_folder" to "بلا مجلد (جميع النصوص)"
        ),
        "fr" to mapOf(
            "search_hint" to "Rechercher un titre ou contenu...",
            "all_scripts" to "Tous les scripts",
            "folders" to "Dossiers",
            "reset_filters" to "Réinitialiser les filtres",
            "delete" to "Supprimer",
            "cancel" to "Annuler",
            "create" to "Créer",
            "delete_script_title" to "Supprimer le script",
            "delete_script_confirm" to "Êtes-vous certain de vouloir supprimer ce script ? Cette opération est irréversible.",
            "delete_folder_title" to "Supprimer le dossier",
            "delete_folder_confirm" to "Supprimer ce dossier ? Les scripts qu’il contient seront conservés et déplacés vers Tous les scripts.",
            "create_folder_title" to "Créer un nouveau dossier",
            "folder_name_hint" to "Nom du dossier (ex., vidéos YouTube)",
            "folder_name_label" to "Nom du dossier",
            "edit_script_tab" to "Modifier le script",
            "saved_key_points_tab" to "Points clés enregistrés",
            "tap_to_jump" to "Appuyer pour sauter & modifier",
            "script_empty_state" to "Le script est vide. Allez sur l'onglet 'Modifier le script' pour rédiger du contenu.",
            "auto_scroll_speed" to "Vitesse de défilement auto",
            "teleprompter_text_size" to "Taille de texte du téléprompteur",
            "background_transparency" to "Transparence de l'arrière-plan",
            "text_color_preset" to "Préréglage couleur ou code Hex personnalisé",
            "visual_customization" to "Personnalisation visuelle",
            "select_theme" to "Choisir le thème coloré de l'app",
            "custom_accent" to "Accentuation de couleur personnalisée",
            "save_apply" to "Enregistrer & Appliquer la personnalisation",
            "text_direction" to "Direction du texte (Support RTL Arabe/Hébreu)",
            "text_direction_auto" to "DÉTECTION AUTO",
            "text_direction_ltr" to "FORCER LTR",
            "text_direction_rtl" to "FORCER RTL",
            "mirror_text" to "Miroir de texte (Inversé)",
            "floating_mode" to "Mode overlay flottant",
            "start_floating" to "Démarrer le téléprompteur flottant",
            "launch_prompter" to "Lancer le téléprompteur",
            "select_tone" to "Choisir le style ou ton",
            "discard_changes" to "Abandonner les modifications",
            "accept_apply" to "Accepter & Appliquer",
            "text_size" to "Taille du texte",
            "backdrop_opacity" to "Opacité de l'arrière-plan",
            "window_opacity" to "Opacité de la fenêtre",
            "speech_color" to "Couleur du texte parlé",
            "backdrop_theme" to "Thème de fond d'écran",
            "default_alignment" to "Alignement par défaut",
            "scroll_speed" to "Vitesse de défilement",
            "save_settings" to "Enregistrer & Appliquer les réglages",
            "words" to "Mots",
            "characters" to "Caractères",
            "voice_calibration" to "Calibrage du style vocal",
            "voice_sensitivity" to "Sensibilité vocale",
            "pause_threshold" to "Seuil de détection des pauses",
            "min_speed" to "Vitesse min (Défilement auto de repli)",
            "max_speed" to "Vitesse max (Sauts de paragraphe)",
            "authorize_now" to "Autoriser maintenant",
            "retry_connection" to "Réessayer la connexion",
            "language_settings" to "Réglages de langue",
            "app_language" to "Langue de l'interface",
            "language_description" to "Remplacer la langue par défaut du téléphone.",
            "all_count" to "Scripts",
            "no_scripts_found" to "Aucun script ne correspond à vos critères.",
            "first_script_prompt" to "Appuyez sur le bouton '+' pour écrire votre premier script !",
            "unassigned_folder" to "Aucun (Tous les scripts)"
        ),
        "de" to mapOf(
            "search_hint" to "Titel oder Inhalt suchen...",
            "all_scripts" to "Alle Skripte",
            "folders" to "Ordner",
            "reset_filters" to "Filter zurücksetzen",
            "delete" to "Löschen",
            "cancel" to "Abbrechen",
            "create" to "Erstellen",
            "delete_script_title" to "Skript löschen",
            "delete_script_confirm" to "Sind Sie sicher, dass Sie dieses Skript löschen möchten? Dies kann nicht rückgängig gemacht werden.",
            "delete_folder_title" to "Ordner löschen",
            "delete_folder_confirm" to "Diesen Ordner löschen? Die enthaltenen Skripte bleiben erhalten und werden zu Alle Skripte verschoben.",
            "create_folder_title" to "Neuen Ordner erstellen",
            "folder_name_hint" to "Ordnername (z.B. YouTube-Videos)",
            "folder_name_label" to "Ordnername",
            "edit_script_tab" to "Skript bearbeiten",
            "saved_key_points_tab" to "Gespeicherte Key-Points",
            "tap_to_jump" to "Tippen zum Springen & Bearbeiten",
            "script_empty_state" to "Das Skript ist leer. Gehen Sie zum Reiter 'Skript bearbeiten', um Inhalt zu schreiben.",
            "auto_scroll_speed" to "Automatische Scrollgeschwindigkeit",
            "teleprompter_text_size" to "Textgröße des Teleprompters",
            "background_transparency" to "Hintergrundtransparenz",
            "text_color_preset" to "Farbvoreinstellung oder benutzerdefiniertes Hex",
            "visual_customization" to "Visuelle Anpassung",
            "select_theme" to "App-Farbschema auswählen",
            "custom_accent" to "Benutzerdefinierte Highlight-Farbe",
            "save_apply" to "Anpassung speichern & anwenden",
            "text_direction" to "Textrichtung (RTL Arabisch/Hebräisch Support)",
            "text_direction_auto" to "AUTOM. ERKENNUNG",
            "text_direction_ltr" to "LTR ERZWINGEN",
            "text_direction_rtl" to "RTL ERZWINGEN",
            "mirror_text" to "Text spiegeln",
            "floating_mode" to "Schwebender Overlay-Modus",
            "start_floating" to "Schwebenden Teleprompter starten",
            "launch_prompter" to "Teleprompter starten",
            "select_tone" to "Stil / Ton auswählen",
            "discard_changes" to "Änderungen verwerfen",
            "accept_apply" to "Akzeptieren & Anwenden",
            "text_size" to "Textgröße",
            "backdrop_opacity" to "Hintergrund-Deckkraft",
            "window_opacity" to "Fenster-Deckkraft",
            "speech_color" to "Gesprochene Textfarbe",
            "backdrop_theme" to "Farbschema des Hintergrunds",
            "default_alignment" to "Standard-Ausrichtung",
            "scroll_speed" to "Scrollgeschwindigkeit",
            "save_settings" to "Einstellungen speichern & anwenden",
            "words" to "Wörter",
            "characters" to "Zeichen",
            "voice_calibration" to "Stimmenstil-Kalibrierung",
            "voice_sensitivity" to "Stimmempfindlichkeit",
            "pause_threshold" to "Pausenerkennungsschwelle",
            "min_speed" to "Mindestgeschwindigkeit (Autom. Sicherheitsnetz)",
            "max_speed" to "Höchstgeschwindigkeit (Absatzsprünge)",
            "authorize_now" to "Jetzt autorisieren",
            "retry_connection" to "Verbindung erneut versuchen",
            "language_settings" to "Spracheinstellungen",
            "app_language" to "App-Schnittstellensprache",
            "language_description" to "Überschreiben Sie die Standard-Spracheinstellung des Telefons.",
            "all_count" to "Skripte",
            "no_scripts_found" to "Keine Skripte stimmen mit Ihren Filtern überein.",
            "first_script_prompt" to "Tippen Sie auf das '+'-Symbol, um Ihr erstes Teleprompter-Skript zu schreiben!",
            "unassigned_folder" to "Keiner (Alle Skripte)"
        ),
        "id" to mapOf(
            "search_hint" to "Cari judul atau konten...",
            "all_scripts" to "Semua Skrip",
            "folders" to "Folder",
            "reset_filters" to "Atur Ulang Filter",
            "delete" to "Hapus",
            "cancel" to "Batal",
            "create" to "Buat",
            "delete_script_title" to "Hapus Skrip",
            "delete_script_confirm" to "Apakah Anda yakin ingin menghapus skrip ini? Tindakan ini tidak dapat dibatalkan.",
            "delete_folder_title" to "Hapus Folder",
            "delete_folder_confirm" to "Hapus folder ini? Skrip di dalamnya akan tetap disimpan dan dipindahkan ke Semua Skrip.",
            "create_folder_title" to "Buat Folder Baru",
            "folder_name_hint" to "Nama Folder (mis., video YouTube)",
            "folder_name_label" to "Nama Folder",
            "edit_script_tab" to "Edit Skrip",
            "saved_key_points_tab" to "Poin Penting Tersimpan",
            "tap_to_jump" to "Ketuk untuk lompat & edit",
            "script_empty_state" to "Skrip kosong. Buka tab 'Edit Skrip' untuk menulis konten.",
            "auto_scroll_speed" to "Kecepatan gulir otomatis",
            "teleprompter_text_size" to "Ukuran teks teleprompter",
            "background_transparency" to "Transparansi latar belakang",
            "text_color_preset" to "Warna teks prasetel atau Hex kustom",
            "visual_customization" to "Kustomisasi Visual",
            "select_theme" to "Pilih Tema Warna Aplikasi",
            "custom_accent" to "Sorotan Aksen Kustom",
            "save_apply" to "Simpan & Terapkan Kustomisasi",
            "text_direction" to "Arah Teks (Dukungan RTL Arab/Ibrani)",
            "text_direction_auto" to "DETEKSI OTOMATIS",
            "text_direction_ltr" to "PAKSA LTR",
            "text_direction_rtl" to "PAKSA RTL",
            "mirror_text" to "Cerminkan Tampilan Teks",
            "floating_mode" to "Mode overlay melayang",
            "start_floating" to "Mulai Pengarah Melayang",
            "launch_prompter" to "Mulai Teleprompter",
            "select_tone" to "Pilih Gaya / Nada",
            "discard_changes" to "Buang Perubahan",
            "accept_apply" to "Terima & Terapkan",
            "text_size" to "Ukuran Teks",
            "backdrop_opacity" to "Opasitas Latar Belakang",
            "window_opacity" to "Opasitas Jendela",
            "speech_color" to "Warna Teks Ucapan",
            "backdrop_theme" to "Tema Warna Latar Belakang",
            "default_alignment" to "Penyelarasan Layar Default",
            "scroll_speed" to "Kecepatan Gulir",
            "save_settings" to "Simpan & Terapkan Pengaturan",
            "words" to "Kata",
            "characters" to "Karakter",
            "voice_calibration" to "Kalibrasi Gaya Suara",
            "voice_sensitivity" to "Sensitivitas Suara",
            "pause_threshold" to "Ambang Deteksi Jeda",
            "min_speed" to "Kecepatan Min (Cadangan Gulir otomatis)",
            "max_speed" to "Kecepatan Maks (Lompatan Paragraf)",
            "authorize_now" to "Otorisasi Sekarang",
            "retry_connection" to "Mencoba Kembali Koneksi",
            "language_settings" to "Pengaturan Bahasa",
            "app_language" to "Bahasa Antarmuka",
            "language_description" to "Ganti pengaturan bahasa default telepon.",
            "all_count" to "Skrip",
            "no_scripts_found" to "Tidak ada skrip yang cocok dengan filter saat ini.",
            "first_script_prompt" to "Ketuk tombol '+' untuk menulis skrip teleprompter pertama Anda!",
            "unassigned_folder" to "Tidak ada (Semua Skrip)"
        ),
        "tr" to mapOf(
            "search_hint" to "Başlık veya içerik ara...",
            "all_scripts" to "Tüm Metinler",
            "folders" to "Klasörler",
            "reset_filters" to "Filtreleri Sıfırla",
            "delete" to "Sil",
            "cancel" to "İptal",
            "create" to "Oluştur",
            "delete_script_title" to "Metni Sil",
            "delete_script_confirm" to "Bu metni silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
            "delete_folder_title" to "Klasörü Sil",
            "delete_folder_confirm" to "Bu klasör silinsin mi? İçindeki metinler korunacak ve Tüm Metinler bölümüne taşınacak.",
            "create_folder_title" to "Yeni Klasör Oluştur",
            "folder_name_hint" to "Klasör Adı (örn., YouTube videoları)",
            "folder_name_label" to "Klasör Adı",
            "edit_script_tab" to "Metni Düzenle",
            "saved_key_points_tab" to "Kaydedilmiş Önemli Noktalar",
            "tap_to_jump" to "Atlamak ve düzenlemek için dokunun",
            "script_empty_state" to "Metin boş. İçerik yazmak için 'Metni Düzenle' sekmesine gidin.",
            "auto_scroll_speed" to "Otomatik kaydırma hızı",
            "teleprompter_text_size" to "Teleprompter yazı boyutu",
            "background_transparency" to "Arka plan şeffaflığı",
            "text_color_preset" to "Yazı rengi şablonu veya Özel Hex",
            "visual_customization" to "Görsel Özelleştirme",
            "select_theme" to "Uygulama Renk Temasını Seçin",
            "custom_accent" to "Özel Vurgu Renkleri",
            "save_apply" to "Özelleştirmeyi Kaydet ve Uygula",
            "text_direction" to "Yazı Yönü (RTL Arapça/İbranice desteği)",
            "text_direction_auto" to "OTOMATİK TESPİT",
            "text_direction_ltr" to "LTR YAP",
            "text_direction_rtl" to "RTL YAP",
            "mirror_text" to "Metni Aynala (Yatay Ters)",
            "floating_mode" to "Yüzen Pencere Modu",
            "start_floating" to "Yüzen Hatırlatıcıyı Başlat",
            "launch_prompter" to "Teleprompter'ı Başlat",
            "select_tone" to "Tarz / Ton Seçin",
            "discard_changes" to "Değişiklikleri At",
            "accept_apply" to "Kabul Et ve Uygula",
            "text_size" to "Metin Boyutu",
            "backdrop_opacity" to "Arka Plan Opaklığı",
            "window_opacity" to "Pencere Opaklığı",
            "speech_color" to "Konuşma Yazısı Rengi",
            "backdrop_theme" to "Arka Plan Renk Teması",
            "default_alignment" to "Varsayılan Ekran Hizalaması",
            "scroll_speed" to "Kaydırma Hızı",
            "save_settings" to "Ayarları Kaydet ve Uygula",
            "words" to "Kelime",
            "characters" to "Karakter",
            "voice_calibration" to "Ses Tarzı Kalibrasyonu",
            "voice_sensitivity" to "Ses Hassasiyeti",
            "pause_threshold" to "Duraklama Algılama Eşiği",
            "min_speed" to "Min Hız (Otomatik Kaydırma Yedeği)",
            "max_speed" to "Maks Hız (Paragraf Atlamaları)",
            "authorize_now" to "Şimdi Yetkilendir",
            "retry_connection" to "Bağlantıyı Yeniden Dene",
            "language_settings" to "Dil Ayarları",
            "app_language" to "Arayüz Dili",
            "language_description" to "Varsayılan telefon dil ayarını devre dışı bırakın.",
            "all_count" to "Metinler",
            "no_scripts_found" to "Mevcut filtrelere uyan hiçbir metin bulunamadı.",
            "first_script_prompt" to "İlk teleprompter metninizi yazmak için '+' düğmesine dokunun!",
            "unassigned_folder" to "Hiçbiri (Tüm Metinler)"
        ),
        "ja" to mapOf(
            "search_hint" to "タイトルまたはコンテンツを検索...",
            "all_scripts" to "すべてのスクリプト",
            "folders" to "フォルダ",
            "reset_filters" to "フィルターをリセット",
            "delete" to "削除",
            "cancel" to "キャンセル",
            "create" to "作成",
            "delete_script_title" to "スクリプトを削除",
            "delete_script_confirm" to "このスクリプトを削除してもよろしいですか？この操作は取り消せません。",
            "delete_folder_title" to "フォルダを削除",
            "delete_folder_confirm" to "このフォルダーを削除しますか？中のスクリプトは保持され、「すべてのスクリプト」に移動します。",
            "create_folder_title" to "新しいフォルダを作成",
            "folder_name_hint" to "フォルダ名 (例: YouTube 動画)",
            "folder_name_label" to "フォルダ名",
            "edit_script_tab" to "スクリプト登録/編集",
            "saved_key_points_tab" to "保存された重要箇所",
            "tap_to_jump" to "タップして移動＆編集",
            "script_empty_state" to "スクリプトが空です。「スクリプト登録/編集」タブで文章を入力してください。",
            "auto_scroll_speed" to "自動スクロール初期速度",
            "teleprompter_text_size" to "プロンプター文字サイズ",
            "background_transparency" to "背景透過度",
            "text_color_preset" to "文字色プリセットまたはカスタムHex値",
            "visual_customization" to "視覚カスタマイズ",
            "select_theme" to "アプリのテーマ色を選択",
            "custom_accent" to "カスタムアクセントカラー",
            "save_apply" to "カスタマイズを保存し適用",
            "text_direction" to "文章方向（RTL アラビア語/ヘブライ語対応）",
            "text_direction_auto" to "自動検出",
            "text_direction_ltr" to "左横書きに固定 (LTR)",
            "text_direction_rtl" to "右横書きに固定 (RTL)",
            "mirror_text" to "反射ミラー表示",
            "floating_mode" to "フローティング重ねて表示",
            "start_floating" to "フローティングプロンプター起動",
            "launch_prompter" to "プロンプター起動",
            "select_tone" to "スタイル / トーン選択",
            "discard_changes" to "変更を破棄",
            "accept_apply" to "承認して適用",
            "text_size" to "テキストサイズ",
            "backdrop_opacity" to "背景の不透明度",
            "window_opacity" to "ウィンドウの不透明度",
            "speech_color" to "音声テキスト色",
            "backdrop_theme" to "背景カラーテーマ",
            "default_alignment" to "デフォルトの配置方向",
            "scroll_speed" to "スクロール速度",
            "save_settings" to "変更を保存し適用",
            "words" to "単語数",
            "characters" to "文字数",
            "voice_calibration" to "音声認識の最適化",
            "voice_sensitivity" to "音声感度",
            "pause_threshold" to "無音のポーズ検出判定閾値",
            "min_speed" to "最小速度（自動スクロール下限値）",
            "max_speed" to "最大速度（段落スキップ時の上限値）",
            "authorize_now" to "承認する",
            "retry_connection" to "再接続を試行",
            "language_settings" to "言語設定",
            "app_language" to "インターフェース言語",
            "language_description" to "携帯電話 of デフォルト言語設定を上書きします。",
            "all_count" to "スクリプト",
            "no_scripts_found" to "現在のフィルターに一致するスクリプトがありません。",
            "first_script_prompt" to "「+」ボタンをタップして、最初のプロンプタースクリプトを作成しましょう！",
            "unassigned_folder" to "なし (すべてのスクリプト)"
        )
    )

    fun get(key: String): String {
        val activeLang = if (currentLanguage == "system") {
            val sysLang = java.util.Locale.getDefault().language
            if (translations.containsKey(sysLang)) sysLang else "en"
        } else {
            if (translations.containsKey(currentLanguage)) currentLanguage else "en"
        }
        return translations[activeLang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
